### ISSUE TITLE
Per-table schema setting

### ISSUE THREAD

**Issue by warent** [dosco/graphjin#143]
**What would you like to be added**:

something like:
```yaml
roles:
  - name: user
    tables:
      - name: users
         schema: my_schema
         query:
           filters: ["{ id: { _eq: $user_id } }"]
```

**Why is this needed**:

Under the "roles" config params, you can specify users and tables, but if your table is in a schema that is different from the one specified at the top of the yaml file, there's no way to access it.

Different tables can live in different schemas. At the moment I think super-graph assumes all your data is architected into one schema.
