### ISSUE TITLE
Setting schema that doesn't exist fails setup

### ISSUE THREAD

**Issue by warent** [dosco/graphjin#144]
### What version of Super Graph are you using? `super-graph version`
v0.15.3

### Steps to reproduce the issue (config used to run Super Graph).

When you specify a schema in your config:
```

database:
  type: postgres
  host: localhost
  port: 5432
  dbname: db
  user: postgres
  password: postgres
  schema: my_schema
```

and run db:setup

It complains in Postgres:

```
ERR failed to initializing migrator: ERROR: no schema has been selected to create in (SQLSTATE 3F000)
```

I'm pretty sure it's trying to use the schema before it exists.

### Expected behaviour and actual result.

The db:setup script should create the default schema it's trying to use if it doesn't already exist.
