### ISSUE TITLE
DB auth handler

### ISSUE THREAD

**Issue by sarendsen** [dosco/graphjin#164]
Im more then willing to create a PR for this.

**What would you like to be added**:

A new auth handler that uses a DB query to authenticate the request.

**Why is this needed**:

Im using token authentication (not JWT) which are stored in the DB.

ex:

```
header_variables:
  auth_token: "Authorization"

auth:
  db:
    query: 'select user_id from auth_token where token = $auth_token'
```
