### ISSUE TITLE
Incorrect log message: 'Field skipped: sometablename, Requires $user_id'

### ISSUE THREAD

**Issue by diegosz** [dosco/graphjin#188]
An incorrect log message 'Field skipped: credentials, Requires $user_id' is printed.

For example, let's say I have a rol `admin` with this table definition:

```yml
roles:
  - name: admin
    match: user_role = 'adm'
    tables:
      - name: credentials
        query:
          filters: ["{ account_id: { eq: $account_id } }"]
          columns: ["id", "account_id", "user_id", "user_role", "user_label"]
          aggregation: true
          disable_functions: true
```

I do all the queries without any incorrect log message.

Then, I add this table definition for the rol `user`:

```yml
roles:
  - name: user
      - name: credentials
        query:
          block: true
```

All the queries works fine, but now you have the incorrect log message: 'Field skipped: credentials, Requires $user_id'

The log message is printed here:

```go
// line 361 core/core.go
func (c *scontext) debugLog(st *stmt) {
	for _, sel := range st.qc.Selects {
		if sel.SkipRender == qcode.SkipTypeUserNeeded {
			c.gj.log.Printf("Field skipped: %s, Requires $user_id", sel.FieldName)
		}
	}
}
```

It's printed becase `SkipRender` is classified as`SkipTypeUserNeeded`.

Apparently the problem is that in this place it's classifed without validating that the rol is `anon`:

```go
// line 357 core/internal/qcode/qcode.go
		if tr.isSkipped(qc.Type) {
			sel.SkipRender = SkipTypeUserNeeded
		} else {
			if err := tr.isBlocked(qc.SType, field.Name); err != nil {
				return err
			}
		}
```

In the rest of the places the `anon` rol is checked prior classifying as `SkipTypeUserNeeded`:

```go
// line 376 core/internal/qcode/qcode.go
		if un := addFilters(qc, &sel.Where, tr); un && role == "anon" {
			sel.SkipRender = SkipTypeUserNeeded
		}

// line 882 core/internal/qcode/qcode.go
	if nu && role == "anon" {
		sel.SkipRender = SkipTypeUserNeeded
	}
	setFilter(&sel.Where, ex)
	return nil
```

Don't know the logic of the `SkipRender`, but it seems that '&& role == "anon"' is missing or another SkipType is needed.
