### ISSUE TITLE
Using PostGIS plugin with GraphJin

### ISSUE THREAD

**Issue by virtumonde** [dosco/graphjin#192]
Hi! I would like to know if GraphJin supports PostGIS ```geometry``` types or custom types in general. By this I mean both inserting and retrieving rows with ```geometry```. I am specifically interested in using [ST_Point](https://postgis.net/docs/ST_Point.html).

**Comment by dosco** [comment]
Not at the moment but I'd like to add this capability. Can you point me to a Postgres docker image with PostGIS installed I had some trouble installing it myself the last time I tried. Currently the only way you can use PostGIS is if you put the gis queries behind Postgres views and just access the view in GraphJin.

**Comment by virtumonde** [comment]
I think [this](https://github.com/postgis/docker-postgis) should work. Thanks for you reply in this issue and the other one too!

**Comment by diegosz** [comment]
Hi, I was able to start graphjin against postgis/postgis in docker-compose.yml:

```yml
version: "3"

networks:
  intranet:

services:

  postgres:
    image: postgis/postgis:13-master
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      intranet:
        aliases:
          - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webshop_development
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata:rw
    restart: unless-stopped

  graphjin:
    image: localbuild-graphjin:v0.16.14test2
    environment:
      - GO_ENV=development
      - WAIT_FOR_HOST=postgres
      - WAIT_FOR_PORT=5432
    volumes:
      - ./config:/config
      - ./keys:/keys/
    ports:
      - "8080:8080"
    networks:
      intranet:
        aliases:
          - graphjin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
```

You have to define 'POSTGRES_DB=webshop_development', because postgis/postgis run this scrip to initialize the db: https://github.com/postgis/docker-postgis/blob/master/initdb-postgis.sh

Also you have to define this variables for graphjin:
      - WAIT_FOR_HOST=postgres
      - WAIT_FOR_PORT=5432

They are for waiting in the start.sh script, I'm sending a pull request for this.
