### ISSUE TITLE
debugging via docker and webui using gebug

### ISSUE THREAD

**Issue by gedw99** [dosco/graphjin#234]
**What would you like to be added**:

ability to debug the local and remote docker.

**Why is this needed**:

I think that its going to make it much easier for others to locate and fix bugs in the code, and hopefully then get higher quality PR's etc as well as devs self diagnosing.

I am using this https://github.com/moshebe/gebug and it works very well.
i think its a good choice for integration into graphjin because all that is needed is a .gebug folder with the settlings in it.

The web ui is also useful.  It also works with different IDE's. I use vscode with it.

The bash API looks like this:
```

then: gebug start  {working dir}--skip-generate 

then: gebug ui  {working dir}--skip-generate 

```

These are the 3 things used. 
gebug can generate them for you if you want.

config.yml:
```
name: ws
output_binary: /app
build_command: go build -o /app
build_dir: ""
run_command: /app
runtime_image: golang:1.15.2
debugger_enabled: true
debugger_port: 40000
expose_ports: []
networks: []
environment: []
```

docker:
```

FROM golang:1.15.2
RUN go get github.com/githubnemo/CompileDaemon
RUN go get github.com/go-delve/delve/cmd/dlv
WORKDIR /src
COPY . .

RUN go build -gcflags="all=-N -l" -o /app
ENTRYPOINT dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec /app

```

docker-compose.yml

```
version: '3'
services:
  gebug-ws:
    build:
      context: ..
      dockerfile: .gebug/Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../:/src:ro
    ports:
      - 40000:40000
  
```
