### ISSUE TITLE
JSONB Tables

### ISSUE THREAD

**Issue by gcemaj** [dosco/graphjin#316]
Following the jsonb example and trying to query results in 

```
{
  "errors": [
    {
      "message": "ERROR: cannot call jsonb_to_recordset on a non-array (SQLSTATE 22023)"
    }
  ]
}
```

### What version of GraphJin are you using? `graphjin version`
0.17.12

### Have you tried reproducing the issue with the latest release?
Yes

### Steps to reproduce the issue (config used to run GraphJin).
Loaded example config using JSONB tables from the docs

```
tables:
  - name: users   
  - name: json_column
    table: users
    type: jsonb
    columns:
      - name: val1
        type: int
      - name: val2
        type: text
```

### Expected behaviour and actual result.
Be able to query jsonb columns
