### ISSUE TITLE
pgadmin docker container included in standard docker compose template

### ISSUE THREAD

**Issue by joeblew99** [dosco/graphjin#345]
**What would you like to be added**:

It would be useful to run pgadmin as a docker container. Its web based and easy to setup.

It would be added to this file: https://github.com/dosco/graphjin/blob/master/internal/cmd/tmpl/docker-compose.yml

**Why is this needed**:

So you can debug easily and do ops easily. 

Also you have self contained setup on a single server, not relying on having pgadmin installed on your laptop. 

I guess in production, you miht want to protect this using wireguard or other, but thats another topic.

---

Here is my working docker compose which has postgres and pgadmin working.

I am not sure how best to adapt this to the docker-compose.yml template yet and hoping that this helps move it forward.

docker-compose.yml
``` 
version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: joe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
``` 

``` 

docker-compose up -d


docker ps

CONTAINER ID   IMAGE            COMMAND                  CREATED             STATUS             PORTS                                            NAMES
92264ade8064   postgres         "docker-entrypoint.s…"   About an hour ago   Up About an hour   0.0.0.0:54320->5432/tcp, :::54320->5432/tcp      local_pgdb
96c52b28c60d   dpage/pgadmin4   "/entrypoint.sh"         About an hour ago   Up About an hour   443/tcp, 0.0.0.0:5050->80/tcp, :::5050->80/tcp   pgadmin4_container

```

I needed to run **docker inspect 92264ade8064**, to find out the IP address of the postres db. 

At the very bottom of the long result you can see the IP address of the postres db that you will need in the PGAdmin web GUI. In my case it was 172.21.0.2.

``` 
docker inspect 92264ade8064

"Networks": {
                "pgadmin_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "local_pgdb",
                        "db",
                        "92264ade8064"
                    ],
                    "NetworkID": "8f4e2e7ad541f28115868813e9e36c5942754e239704a6d614c56dfce0493627",
                    "EndpointID": "d0dfcfc0c6e2104474ca0b564ba32402d78189d21008811e34c44bb63bab2164",
                    "Gateway": "172.21.0.1",
                    "IPAddress": "172.21.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:15:00:02",
                    "DriverOpts": null
                }
            }


```

Now open the browser at http://localhost:5050/, login using the email and password ( in the docker file ), and then create a server using the IP Address from above.

![Screenshot 2022-04-07 at 13 16 11](https://user-images.githubusercontent.com/11999859/162186937-32e6c1e8-1779-4105-86bd-35a6ad5c1f19.png)
