### ISSUE TITLE
Graphjin unable to find tables in Postgres 16

### ISSUE THREAD

**Issue by rkrishnasanka** [dosco/graphjin#515]
It seems like Graphjin is unable to find the tables or errors during the the initialization saying that there are no tables found when using postgres 16. I noticed issue when my development containers were rebuilt and the postgres version went from 15->16. For now I'm locking my development environment to 15 until this is resolved for graphjin.

### What version of GraphJin are you using? `graphjin version`
From mod file:
```
github.com/dosco/graphjin/core/v3 v3.0.0-20231214230854-91d9d01a55dc // indirect
```

### Have you tried reproducing the issue with the latest release?
No

### What is the hardware spec (RAM, OS)?
MacOS, 16GB

### Steps to reproduce the issue (config used to run GraphJin).
1. Use postgres 16 as the database using docker / docker-compose
2. Initialize the data
3. Run the `serv` code
4. See it end the server saying that it cannot find tables

### Expected behaviour and actual result.
Should kind of just keep working. 

Here is the docker compose I'm using:

```yaml
version: '3.8'

volumes:
  postgres-data:
  minio_data_container:

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    network_mode: host

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  s3local:
    image: minio/minio
    volumes:
      - minio_data_container:/data/s3
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server /data/s3 --console-address ":9001"
    restart: unless-stopped
    network_mode: host
```
