### ISSUE TITLE
CRUD roles inheriting

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#87]
Let's take the example config [here](https://supergraph.dev/docs/config):

```yaml
roles:
  - name: user
    tables:
      - name: products
        query:
          filters: ["{ user_id: { eq: $user_id } }"]
        insert:
          filters: ["{ user_id: { eq: $user_id } }"]
        update:
          filters: ["{ user_id: { eq: $user_id } }"]
```

As you can see we're repeating multiple times the string:

```
["{ user_id: { eq: $user_id } }"]
```

It would be amazing to have something like:

```yaml
roles:
  - name: user
    tables:
      - name: products
        crud:
          filters: ["{ user_id: { eq: $user_id } }"]
        query:
          # here it is inherited crud's "filters"
        insert:
          # here it is inherited crud's "filters"
        update:
          # here it is inherited crud's "filters"
```

And not just for `filters`: any!

(_And the same in SuperGraph as a library Golang config, of course._)

Don't you think, @dosco?

**Comment by dosco** [comment]
I don't think you need `filters: ["{ user_id: { eq: $user_id } }"]` for `insert` the returned values will be limited to what you have inserted. See the below example

```
tables:
  - name: me
    table: users

roles:
  - name: user
     tables:
      - name: me
        query:
          filters: ["{ id: { eq: $user_id } }", "{ disabled: { neq: true } }"]
        update:
          filters: ["{ id: { eq: $user_id } }", "{ disabled: { neq: true } }"]
          presets:
            - updated_at: "now"

    - name: posts
        insert:
          presets:
            - user_id: "$user_id"
            - created_at: "now"
            - updated_at: "now"
```
